on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libvips-tools
      - name: Info
        run: ffmpeg -version; vips --version; chrome --version
      - name: Install
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
