on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
      - name: Install vips-tools
        run: sudo apt-get update; sudo apt-get install -y libvips-tools
      - name: Info
        run: ffmpeg -version; vips --version; chromium --version
      - name: Install
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        env:
          MK_NOSBX: 1
        run: go test ./...
